favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://pnv-refuge-arpont.brgm-rec.fr/themes/custom/refuges/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  refuges: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://LogoRefuge_14.png'
  url: ''
  use_default: 0
region_wells:
  navigation: ''
  navigation_collapsible: ''
  top: ''
  header: ''
  hamburger: ''
  highlighted: ''
  help: ''
  content: ''
  post_content_1: ''
  post_content_2: ''
  sidebar_first: ''
  sidebar_second: ''
  pre_footer: ''
  footer: ''
table_responsive: '-1'
table: ''
cdn_provider_import_data: ''
langcode: fr
