taxonomies:
  icons:
    -
      vid: icons
      tid: '1'
      langcode: fr
      name: 'Plaque de cuisson'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1a278a97-6ce8-4ba7-9e7a-43ffd39d7484
    -
      vid: icons
      tid: '2'
      langcode: fr
      name: Bar
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 48df6786-300c-4376-aae1-baeaf6e7f121
    -
      vid: icons
      tid: '3'
      langcode: fr
      name: 'Accès handicapé'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: d0291a95-b585-40cc-b07a-5cff444ecc7c
    -
      vid: icons
      tid: '4'
      langcode: fr
      name: 'Balise radio'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 6f57a6de-0982-4b5d-bd6e-a81e6092d354
    -
      vid: icons
      tid: '5'
      langcode: fr
      name: Bivouac
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 037e3ec4-87a8-4944-ae28-5315688a031e
    -
      vid: icons
      tid: '6'
      langcode: fr
      name: CB
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ed9feb22-41f4-4151-bb42-dd3d12346594
    -
      vid: icons
      tid: '7'
      langcode: fr
      name: Chauffage
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 15a66a05-a193-48b7-a99a-1bf14c332907
    -
      vid: icons
      tid: '8'
      langcode: fr
      name: Couverture
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1e3361a5-ad67-4394-b611-75092e653954
    -
      vid: icons
      tid: '9'
      langcode: fr
      name: Defebrilateur
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 4dc01705-2ff6-41e7-9c0b-a02d2393b522
    -
      vid: icons
      tid: '10'
      langcode: fr
      name: Dortoirs
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 70b7c3a7-fb55-4529-b597-72e755e3858d
    -
      vid: icons
      tid: '11'
      langcode: fr
      name: Douche
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1afb253a-8e5d-435d-b544-75ee57891dea
    -
      vid: icons
      tid: '12'
      langcode: fr
      name: 'Eau potable'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: f2419efc-c117-4d9d-b7ff-b50e47759c38
    -
      vid: icons
      tid: '13'
      langcode: fr
      name: Lumière
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 4c0b712c-19e9-4e62-8182-bbf9e7b48e50
    -
      vid: icons
      tid: '14'
      langcode: fr
      name: 'Nombre de couchage'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: ffc6bc7a-774f-4700-a408-22964de953ef
    -
      vid: icons
      tid: '15'
      langcode: fr
      name: Pharmacie
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 44f3bacf-2863-42a0-be38-82d766fb1ad9
    -
      vid: icons
      tid: '16'
      langcode: fr
      name: 'Prise electrique'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 2f463a7f-7004-424e-bfe2-eb6950f9a0a9
    -
      vid: icons
      tid: '17'
      langcode: fr
      name: Restauration
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: b815589b-919d-46fe-ab0c-79917255689a
    -
      vid: icons
      tid: '18'
      langcode: fr
      name: 'Salle hors sac'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 30aba1d1-282c-4bf2-87cb-03990b7c096b
    -
      vid: icons
      tid: '19'
      langcode: fr
      name: Toilettes
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 81db971c-315d-44ae-9fe9-a1780e52ee08
    -
      vid: icons
      tid: '20'
      langcode: fr
      name: Vaisselle
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7f93e49a-6c8d-4f26-af6a-0efdf2bd016f
    -
      vid: icons
      tid: '21'
      langcode: fr
      name: Wifi
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 220fc1a5-9e9a-4eed-afd2-328d05551700
blocks:
  -
    info: 'Coordonnées du refuge'
    langcode: und
    uuid: 50ce15fb-0214-4fcb-8c36-91f3c7ed7899
    bundle: contact_details
    revision_id: null
    rev_id_current: null
    fields:
      field_email:
        value: refuge.arpont@vanoise-parcnational.fr
      field_phone:
        value: '+33 9 82 12 42 13'
      field_postal_address:
        value: "rue Parrachée\r\n73500 TERMIGNON"
  -
    info: Partenaires
    langcode: und
    uuid: 9b2300b4-38a4-407d-bf8f-14cc8c61fbc5
    bundle: bloc_partenaires
    revision_id: null
    rev_id_current: null
    fields:
      field_partner_logo:
        target_id: '4'
        alt: 'Esprit Parc National'
        title: ''
        width: '280'
        height: '202'
        link_uri: 'http://www.espritparcnational.com/parcs-nationaux/parc-national-de-la-vanoise'
        link_title: null
        link_options: {  }
        link_display_settings:
          formatter_settings: false
          image_link: ''
          link_title_display: false
          link_title_tag: ''
          link_title_position: ''
          link_rel: false
          link_target: false
  -
    info: 'Bloc d''intro de la page Services'
    langcode: fr
    uuid: 6d6f6b90-7ad4-4506-91dd-efb85fe52a20
    bundle: intro_block
    revision_id: null
    rev_id_current: null
    fields:
      field_intro_block_footer:
        value: "<p>En période :</p>\r\n"
        format: full_html
      field_intro_block_header: null
      field_intro_block_text:
        value: "<p>Lorem ipsum dolor sit amet,sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, &nbsp;At vero eos et accusam et justo duo dolores et ea rebum. &nbsp;Lorem ipsum dolor sit amet, &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;Stet clita kasd gubergren, &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;no sea takimata sanctus est Lorem ipsum dolor sit amet. &nbsp;sed diam voluptua. &nbsp;</p>\r\n"
        format: full_html
      field_intro_block_title:
        value: 'Sous-titre de la page Services'
menus:
  -
    menu_name: refuges
    title: 'Refuge de l''Arpont'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-arpont.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: fr
    uuid: 680cc1a1-3c76-47c7-88bc-4c7394f16b84
  -
    menu_name: refuges
    title: 'Refuge du Col du Palet'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-coldupalet.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: fr
    uuid: 575b0ca3-2514-407b-88f4-205aa337a1f5
  -
    menu_name: refuges
    title: 'Les autres refuges'
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '1'
    weight: '0'
    langcode: fr
    uuid: 037c2d04-7afe-4be6-904e-a4ceef151823
  -
    menu_name: refuges
    title: 'Refuge-porte du Bois'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-dubois.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-39'
    langcode: fr
    uuid: 0c075c57-37d4-482b-8690-91279eed6a42
  -
    menu_name: refuges
    title: 'Refuge de la Femma'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-femma.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: fr
    uuid: 0e1f5be6-d2a9-4ffc-8aed-f53a9653bcfc
  -
    menu_name: refuges
    title: 'Refuge du Fond des Fours'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-fonddesfours.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: fr
    uuid: 8212702d-a6bd-4088-ab28-f031aa617fd7
  -
    menu_name: refuges
    title: 'Refuge de la Martin'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-lamartin.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: fr
    uuid: 5f17d90d-8212-4dfe-8db0-117a07df58c7
  -
    menu_name: refuges
    title: 'Refuge de la Leisse'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-leisse.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: fr
    uuid: faf73d2b-2e10-4328-9482-de8cb0b82d9f
  -
    menu_name: refuges
    title: 'Refuge-porte de l''Orgère'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-orgere.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-38'
    langcode: fr
    uuid: 35c235c5-70d1-4b54-a5f2-4e3f45f41b35
  -
    menu_name: refuges
    title: 'Refuge de Plaisance'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-plaisance.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-44'
    langcode: fr
    uuid: e5491a50-3f11-4796-afb8-116ba9181c9a
  -
    menu_name: refuges
    title: 'Refuge-porte de Plan du Lac'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-plandulac.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-37'
    langcode: fr
    uuid: e3d7d367-cc75-4d44-ac22-a81ffc058071
  -
    menu_name: refuges
    title: 'Refuge de Prariond'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-prariond.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-43'
    langcode: fr
    uuid: e2c10115-7e9a-4c32-b9f9-71407196d230
  -
    menu_name: refuges
    title: 'Refuge-porte de Rosuel'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-rosuel.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-36'
    langcode: fr
    uuid: 7995f86e-eed8-4c70-be45-1d901b86bf9c
  -
    menu_name: refuges
    title: 'refuge de Turia'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-turia.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-42'
    langcode: fr
    uuid: ea2a991a-35ab-4219-a109-21b16e5bd2a2
  -
    menu_name: refuges
    title: 'Refuge de la Valette'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-valette.vanoise.com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-41'
    langcode: fr
    uuid: 41bc4bd7-6fdc-4d7f-b489-9e0d9ca44c8b
  -
    menu_name: refuges
    title: 'Refuge de Vallonbrun'
    parent: 'menu_link_content:037c2d04-7afe-4be6-904e-a4ceef151823'
    uri: 'http://refuge-vallonbrun.vanoise-com'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-40'
    langcode: fr
    uuid: 5a4ffbd0-6f2b-4839-84a8-4eddae46114e
  -
    menu_name: menu-hamburger
    title: Media
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '1'
    weight: '12'
    langcode: fr
    uuid: 33dd4068-3750-4636-99fe-cccb079eb74e
  -
    menu_name: menu-hamburger
    title: Services
    parent: null
    uri: 'internal:/services-gardiennage'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '13'
    langcode: fr
    uuid: 4c3dd96b-81f2-4cd1-88cf-53f8535da8be
  -
    menu_name: menu-hamburger
    title: Photos
    parent: 'menu_link_content:33dd4068-3750-4636-99fe-cccb079eb74e'
    uri: 'internal:/galeries-photo'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: fr
    uuid: 07590579-de18-4678-b3b6-52944f9a39fa
  -
    menu_name: menu-hamburger
    title: Vidéos
    parent: 'menu_link_content:33dd4068-3750-4636-99fe-cccb079eb74e'
    uri: 'internal:/videos'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '1'
    langcode: fr
    uuid: 619e4599-8e63-4c71-b1f2-a22fbefb5d6b
  -
    menu_name: menu-hamburger
    title: Documents
    parent: 'menu_link_content:33dd4068-3750-4636-99fe-cccb079eb74e'
    uri: 'internal:/documents'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '2'
    langcode: fr
    uuid: 7a4d8b92-0a43-43e9-9cb0-5b8d83ec3698
