adding:
  settings:
    platforms:
      twitter:
        value: ''
      youtube:
        value: ''
    link_attributes:
      target: _blank
removing:
  settings:
    platforms:
      twitter:
        value: pnvanoise
      youtube:
        value: user/ParcNationalVanoise
    link_attributes:
      target: '<none>'
