adding:
  settings:
    platforms:
      facebook:
        value: RefugeDePrariond/
      twitter:
        value: ''
      youtube:
        value: ''
      instagram:
        value: 'refugedeprariond/?hl=fr'
    link_attributes:
      target: _blank
removing:
  settings:
    platforms:
      facebook:
        value: parcnationaldelavanoise/
      twitter:
        value: pnvanoise
      youtube:
        value: user/ParcNationalVanoise
      instagram:
        value: ''
    link_attributes:
      target: '<none>'
