adding:
  favicon:
    url: 'http://refuge-plandulac.vanoise.com/themes/custom/refuges/favicon.ico'
    use_default: 1
  features:
    comment_user_picture: 1
    comment_user_verification: 1
    favicon: 1
    node_user_picture: 1
  logo:
    path: 'public://logo carré.png'
    use_default: 0
  region_wells:
    navigation: ''
    navigation_collapsible: ''
    top: ''
    header: ''
    hamburger: ''
    highlighted: ''
    help: ''
    content: ''
    post_content_1: ''
    post_content_2: ''
    sidebar_first: ''
    sidebar_second: ''
    pre_footer: ''
    footer: ''
  table_responsive: '-1'
  table: ''
  cdn_provider_import_data: ''
  langcode: fr
removing:
  favicon:
    url: 'http://www.bois2.localhost/themes/contrib/bootstrap/favicon.ico'
    use_default: true
  features:
    comment_user_picture: true
    comment_user_verification: true
    favicon: true
    node_user_picture: true
  logo:
    path: ''
    use_default: true
