credential_provider: shield
credentials:
  shield:
    user: recette-refuges
    pass: RefVan2018!
print: 'Serveur de recette des refuges de la Vanoise'
allow_cli: true
_core:
  default_config_hash: c1dcnGFDXTeMq2-Z8e7H6Qxp6TTJe-ZhSA126E3bQJ4
langcode: fr
